name: Build Linux

on: [workflow_dispatch]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build project
        run: g++ main.cpp

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: a.out
          path: a.out
          retention-days: 1

